-----------------------------------------------------------------------

-- TOTAL SALES ----

SELECT SUM(SALE_TOTAL) AS TOTAL_SALES FROM TBL_FACT_SALES;

-- TOTAL PROFIT --

SELECT SUM(UNIT_PRICE) - SUM(UNIT_COST) AS TOTAL_PROFIT  FROM TBL_FACT_SALES;

-- TOTAL RETURN --

SELECT COUNT(RETURNED_QUANTITY) AS TOTAL_RETURN FROM TBL_FACT_SALES;

-- TOTAL_PROFIT_PERSENTAGE -- 

SELECT 
SUM(UNIT_PRICE) - SUM(UNIT_COST) -
SUM(SALE_TOTAL) * 100 AS TOTAL_PROFIT_PERSENTAGE
FROM TBL_FACT_SALES;

SELECT 
    ( SUM(UNIT_PRICE) - SUM(UNIT_COST )) * 100.0 / SUM(SALE_TOTAL) AS TOTAL_PROFIT_PERCENTAGE
FROM TBL_FACT_SALES;

-- ORDER METHOD BY TOTAL_SALES ---

SELECT 
    O.METHOD_NAME, 
    SUM(F.SALE_TOTAL) AS TOTAL_SALES
FROM TBL_FACT_SALES AS F
LEFT JOIN TBL_DIM_ORDER_METHOD_LKP AS O
    ON F.ORDER_METHOD_KEY = O.METHOD_KEY
GROUP BY METHOD_NAME
ORDER BY SUM(F.SALE_TOTAL) DESC;

-- ORDER METHOD BY TOTAL_ORDER ---

SELECT O.METHOD_NAME, COUNT(SALES_ORDER_KEY) AS TOTAL_ORDER 
FROM TBL_FACT_SALES AS F
LEFT JOIN TBL_DIM_ORDER_METHOD_LKP AS O
ON F.ORDER_METHOD_KEY = O.METHOD_KEY
GROUP BY METHOD_NAME
ORDER BY COUNT(SALES_ORDER_KEY) DESC;

-- FIND TOP 10 PRODUCT SALES WISE --
SELECT TOP 10 P.PRODUCT_NAME, SUM(F.SALE_TOTAL) AS HIGHEST_SALES FROM TBL_DIM_PRODUCT AS P
LEFT JOIN TBL_FACT_SALES AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY PRODUCT_NAME
ORDER BY SUM(F.SALE_TOTAL) DESC;

-- FIND LOWEST 10 PRODUCT SALES WISE --
SELECT TOP 10 P.PRODUCT_NAME, SUM(F.SALE_TOTAL) AS HIGHEST_SALES FROM TBL_DIM_PRODUCT AS P
LEFT JOIN TBL_FACT_SALES AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY PRODUCT_NAME
ORDER BY SUM(F.SALE_TOTAL);

-----------------------------------------------------------------------

-- TOTAL ORDER -- 

SELECT COUNT(SALES_ORDER_KEY) AS TOTAL_ORDER FROM TBL_FACT_SALES;

--- TOTAL ORDER BY PRODUCT ---

SELECT P.PRODUCT_NAME, COUNT(SALES_ORDER_KEY) AS TOTAL_ORDER 
FROM TBL_FACT_SALES AS F
LEFT JOIN TBL_DIM_PRODUCT AS P
ON F.PRODUCT_KEY = P.PRODUCT_KEY
GROUP BY PRODUCT_NAME
ORDER BY COUNT(SALES_ORDER_KEY) DESC;

-- FIND TOTAL ORDERS COUNTRY WISE

SELECT C.COUNTRY_NAME,COUNT(SALES_ORDER_KEY) AS TOTAL_ORDER 
FROM TBL_FACT_SALES AS F
LEFT JOIN TBL_DIM_COUNTRY_LKP AS C
ON F.COUNTRY_KEY = C.COUNTRY_KEY
GROUP BY COUNTRY_NAME
ORDER BY COUNT(SALES_ORDER_KEY) DESC;

---------------------------------------------------------------------

--- FIND PRODUCT NAME WITH HIGHEST SALES ---

SELECT TOP 1 P.PRODUCT_NAME, SUM(F.SALE_TOTAL) AS HIGHEST_SALES 
FROM TBL_DIM_PRODUCT AS P
LEFT JOIN TBL_FACT_SALES AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY PRODUCT_NAME
ORDER BY SUM(F.SALE_TOTAL) DESC;

--- FIND PRODUCT NAME WITH LOWEST SALES ---

SELECT TOP 1 P.PRODUCT_NAME, SUM(F.SALE_TOTAL) AS HIGHEST_SALES 
FROM TBL_DIM_PRODUCT AS P
LEFT JOIN TBL_FACT_SALES AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY PRODUCT_NAME
ORDER BY SUM(F.SALE_TOTAL);

--- FIND OPEN AND CLOSE INVENTRY PRODUCT WISE ---

SELECT P.PRODUCT_NAME, 
SUM(F.OPENING_INVENTORY) AS OPENING_INVENTORY, 
SUM(F.CLOSING_INVENTORY) AS CLOSING_INVENTORY 
FROM TBL_DIM_PRODUCT AS P
LEFT JOIN TBL_FACT_INVENTORY AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY PRODUCT_NAME
ORDER BY SUM(F.OPENING_INVENTORY) DESC, 
SUM(F.CLOSING_INVENTORY) DESC;

-- FIND TOTAL SALE BY CITY ---

SELECT W.CITY, SUM(F.SALE_TOTAL) AS HIGHEST_SALES 
FROM TBL_DIM_WAREHOUSE_LKP AS W
JOIN TBL_FACT_SALES AS F
ON W.BRANCH_CODE = F.COUNTRY_KEY
-- WHERE CITY = 'München'  
GROUP BY CITY
ORDER BY SUM(F.SALE_TOTAL)DESC;

------------------------------------------------------------------------

-- Find Highest Retailer --

SELECT TOP 1 R.RETAILER_NAME, SUM(F.SALE_TOTAL) AS HIGHEST_SALES, 
COUNT(F.SALES_ORDER_KEY) AS TOTAL_ORDER FROM TBL_DIM_RETAILER_LKP AS R
LEFT JOIN TBL_FACT_SALES AS F
ON R.RETAILER_KEY = F.RETAILER_KEY
GROUP BY RETAILER_NAME
ORDER BY SUM(F.SALE_TOTAL) DESC, 
COUNT(F.SALES_ORDER_KEY) DESC;

-- Find Lowest Retailer --

SELECT TOP 1 R.RETAILER_NAME, SUM(F.SALE_TOTAL) AS LOWEST_SALES, 
COUNT(F.SALES_ORDER_KEY) AS TOTAL_ORDER FROM TBL_DIM_RETAILER_LKP AS R
LEFT JOIN TBL_FACT_SALES AS F
ON R.RETAILER_KEY = F.RETAILER_KEY
GROUP BY RETAILER_NAME
ORDER BY SUM(F.SALE_TOTAL), COUNT(F.SALES_ORDER_KEY);

-- WAREHOUSE WISE OPEN AND CLOSE INVENTRY --------

SELECT W.ADDRESS AS WAREHOUSE, 
SUM(F.OPENING_INVENTORY) AS OPENING_INVENTORY, 
SUM(F.CLOSING_INVENTORY) AS CLOSING_INVENTORY 
FROM TBL_DIM_WAREHOUSE_LKP AS W
JOIN TBL_FACT_INVENTORY AS F
ON W.WAREHOUSE_KEY = F.WAREHOUSE_KEY
GROUP BY ADDRESS
ORDER BY SUM(F.OPENING_INVENTORY) DESC, 
SUM(F.CLOSING_INVENTORY) DESC;

-- PRODUCT BRAND WISE TOTAL SALES ---

SELECT P.PRODUCT_BRAND,
SUM(F.SALE_TOTAL) AS TOTAL_SALES
FROM TBL_DIM_PRODUCT AS P
LEFT JOIN TBL_FACT_SALES AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY PRODUCT_BRAND
ORDER BY PRODUCT_BRAND, SUM(F.SALE_TOTAL) DESC;

-- PRODUCT BRAND WISE TOTAL ORDER ---
SELECT P.PRODUCT_BRAND,
COUNT(F.SALES_ORDER_KEY) AS TOTAL_ORDERS
FROM TBL_DIM_PRODUCT AS P
LEFT JOIN TBL_FACT_SALES AS F
ON P.PRODUCT_KEY = F.PRODUCT_KEY
GROUP BY PRODUCT_BRAND
ORDER BY COUNT(F.SALES_ORDER_KEY) DESC;

-----------------------------------------------------------------------

SELECT D.CURRENT_QUARTER, COUNT(SALES_ORDER_KEY) AS TOTAL_ORDER 
FROM TBL_FACT_SALES AS F
LEFT JOIN 
TBL_DIM_DATE_TIME AS D
ON F.SALES_ORDER_KEY = D.DAY_KEY
GROUP BY CURRENT_QUARTER
ORDER BY COUNT(SALES_ORDER_KEY);

-- YEAR WISE TOTAL ORDER

SELECT YEAR(D.DAY_DATE)AS YEAR, COUNT(SALES_ORDER_KEY) AS TOTAL_ORDER 
FROM TBL_FACT_SALES AS F
LEFT JOIN 
TBL_DIM_DATE_TIME AS D
ON F.ORDER_DATE_KEY = D.DAY_KEY
GROUP BY D.DAY_DATE
ORDER BY COUNT(SALES_ORDER_KEY);

SELECT * FROM TBL_DIM_DATE_TIME;

SELECT * FROM TBL_FACT_SALES;